name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # Use Go 1.23.x (latest patch) to match the version declared in go.mod
          go-version: '1.23.x'
          cache: true

      # Ensure automatic toolchain download is enabled. This makes `go` fetch
      # the exact version specified in the `toolchain` directive of go.mod
      # (go1.23.11) if it differs from the pre-installed gotip binary.
      - name: Enable Go toolchain auto-download
        run: echo "GOTOOLCHAIN=auto" >> $GITHUB_ENV

      - name: Download dependencies
        run: go mod download

      - name: Run unit tests
        run: go test ./...

# Install and run golangci-lint 2.2.2 (built with Go ≥1.24)
      - name: Install golangci-lint 2.2.2
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            | sh -s -- -b $(go env GOPATH)/bin v2.2.2

      - name: Run golangci-lint
        run: golangci-lint run --timeout=5m 